2022-10-11 15:45:54,363 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\miche\OneDrive\Desktop\CA_assignment1\pa1\autograde.py", line 973, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\miche\OneDrive\Desktop\CA_assignment1\pa1\autograde.py", line 728, in test_project
    project.build()
  File "C:\Users\miche\OneDrive\Desktop\CA_assignment1\pa1\autograde.py", line 686, in build
    p.build(clear)
  File "C:\Users\miche\OneDrive\Desktop\CA_assignment1\pa1\autograde.py", line 637, in build
    run_command(['make'])
  File "C:\Users\miche\OneDrive\Desktop\CA_assignment1\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "C:\Users\miche\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\miche\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
